### ISSUE TITLE
Css file names do not change when images within the file change content

### ISSUE THREAD

**Issue by tomaslin** [Grailsrocks/grails-cached-resources#3]
We have a css file that embeds an image.

We see the css name is:

gHBlnyf50JPSKJjENrIhdQ2ovgr5iOOi2uvPwWjINoe.css

And the file content is:

``` css
.search {
       background: transparent url(eq8jTXq1Uk56HvVkeeKRKnaxeJGgzqCJ1iSxDFhVgFr.png) 0 0 no-repeat;
}
```

We change the image to another image in the file system, keeping the same name.

this leads to new css content:

``` css
.search {
       background: transparent url(0tX3g00nnE9AAvZVWiuiny5wpFAHdKpQvybjKsKx4CX.png) 0 0 no-repeat;
}
```

However, this does not change the name of the css file. This causes a staleness issue in clients that have already downloaded the css file. 

The correct behaviour should generate a new css name when the contents in the css have changed.
